services:
  db:
    image: postgres:17.2-alpine3.21
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - tenpo-network

  web:
    image: fabianveal/tenpo-web
    build:
      context: ./web
      dockerfile: ../docker/web.dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:8080"
    networks:
      - tenpo-network
    depends_on:
      - server

  server:
    image: fabianveal/tenpo-server
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - tenpo-network
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  tenpo-network:
    driver: bridge
